# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class Book(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, title: str=None, year: int=None, author: str=None, pages: int=None, genre: str=None):  # noqa: E501
        """Book - a model defined in Swagger

        :param id: The id of this Book.  # noqa: E501
        :type id: str
        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param year: The year of this Book.  # noqa: E501
        :type year: int
        :param author: The author of this Book.  # noqa: E501
        :type author: str
        :param pages: The pages of this Book.  # noqa: E501
        :type pages: int
        :param genre: The genre of this Book.  # noqa: E501
        :type genre: str
        """
        self.swagger_types = {
            'id': str,
            'title': str,
            'year': int,
            'author': str,
            'pages': int,
            'genre': str
        }

        self.attribute_map = {
            'id': '_id',
            'title': 'title',
            'year': 'year',
            'author': 'author',
            'pages': 'pages',
            'genre': 'genre'
        }
        self._id = id
        self._title = title
        self._year = year
        self._author = author
        self._pages = pages
        self._genre = genre

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Book.


        :return: The id of this Book.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Book.


        :param id: The id of this Book.
        :type id: str
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Book.


        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.


        :param title: The title of this Book.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def year(self) -> int:
        """Gets the year of this Book.


        :return: The year of this Book.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this Book.


        :param year: The year of this Book.
        :type year: int
        """

        self._year = year

    @property
    def author(self) -> str:
        """Gets the author of this Book.


        :return: The author of this Book.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Book.


        :param author: The author of this Book.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def pages(self) -> int:
        """Gets the pages of this Book.


        :return: The pages of this Book.
        :rtype: int
        """
        return self._pages

    @pages.setter
    def pages(self, pages: int):
        """Sets the pages of this Book.


        :param pages: The pages of this Book.
        :type pages: int
        """

        self._pages = pages

    @property
    def genre(self) -> str:
        """Gets the genre of this Book.


        :return: The genre of this Book.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this Book.


        :param genre: The genre of this Book.
        :type genre: str
        """
        allowed_values = ["novel", "encyclopedia", "comic", "biography", "history"]  # noqa: E501
        if genre not in allowed_values:
            raise ValueError(
                "Invalid value for `genre` ({0}), must be one of {1}"
                .format(genre, allowed_values)
            )

        self._genre = genre
