# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class File_(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None, path: str=None):  # noqa: E501
        """File_ - a model defined in Swagger

        :param title: The title of this File_.  # noqa: E501
        :type title: str
        :param description: The description of this File_.  # noqa: E501
        :type description: str
        :param path: The path of this File_.  # noqa: E501
        :type path: str
        """
        self.swagger_types = {
            'title': str,
            'description': str,
            'path': str
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            'path': 'path'
        }
        self._title = title
        self._description = description
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'File_':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The File_ of this File_.  # noqa: E501
        :rtype: File_
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this File_.


        :return: The title of this File_.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this File_.


        :param title: The title of this File_.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this File_.


        :return: The description of this File_.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this File_.


        :param description: The description of this File_.
        :type description: str
        """

        self._description = description

    @property
    def path(self) -> str:
        """Gets the path of this File_.


        :return: The path of this File_.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this File_.


        :param path: The path of this File_.
        :type path: str
        """

        self._path = path
