#db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  clusterIP: None
  ports:
    - name: "mongo"
      protocol: TCP
      port: 27017
      targetPort: 27017
