apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: fileapp
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
