apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
spec:
  volumeName: web-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
